<?php
/**
 * @file
 * Code for Drupal Kitchen Cookoff
 */

// Load the plugins include, which has a bunch of plugin functions we'll need.
module_load_include('inc', 'dkc_single', 'includes/plugins');

// Load the info include, which has a bunch of info getting functions we'll need.
module_load_include('inc', 'dkc_single', 'includes/info');

// Load the formatting include, which has a bunch of formatting functions we'll need.
module_load_include('inc', 'dkc_single', 'includes/formatting');

// Load the random include, which has some random generation functions that
// plugins will need.
module_load_include('inc', 'dkc_single', 'includes/random');

/**
 * Implements hook_menu().
 */
function dkc_single_menu() {
  $items = array();

  // Start page
  $items['start/single'] = array(
    'title' => t('Start a single player game'),
    'page callback' => 'dkc_single_start',
    'access arguments' => array('play single player'),
    'file' => 'includes/pages.inc',
  );
  // Start page
  $items['start/single/%dkc_level'] = array(
    'title' => t('Single Player Level'),
    'page callback' => 'dkc_single_page',
    'page arguments' => array(2),
    'access arguments' => array('play single player'),
    'file' => 'includes/pages.inc',
  );

  // Score care
  $items['user/%user/score'] = array(
    'title' => t('Score'),
    'page callback' => 'dkc_single_score',
    'page arguments' => array(1),
    'access arguments' => array('play single player'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/pages.inc',
  );

  return $items;
}

/**
 * Level loading function.
 */
function dkc_level_load($level_id) {
  return dkc_single_get_level_plugin($level_id);
}

/**
 * Implements hook_form_alter().
 */
function dkc_single_form_alter(&$form, &$form_state, $form_id) {
  // Check for a level.
  if (!empty($_GET['level'])) {
    // Load the level.
    $level = dkc_single_get_level_plugin($_GET['level']);
    // Store the level data in form_state.
    $form_state['dkc_level'] = $level;

    // Let the level run it's own form alter.
    if ($function = ctools_plugin_get_function($level, 'form_alter')) {
      $function($form, $form_state, $form_id);
    }
  }
}

/**
 * Implements hook_permission().
 */
function dkc_single_permission() {
  return array(
    'play single player' => array(
      'title' => t('Play a single player game of DK Cookoff'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function dkc_single_theme($existing, $type, $theme, $path) {
  return array(
    'score_bar' => array(
      'variables' => array('uid' => NULL),
    ),
  );
}

/**
 * Implements theme_score_bar().
 *
 * @param
 *   $uid - The User ID of the user we want to render a score bar for.
 *
 * @return
 *   A renderable array representing a user's score.
 */
function theme_score_bar($uid = NULL) {
  // Load user.
  if (!empty($uid)) {
    $user = user_load($uid);
  }
  else {
    global $user;
  }

  // Start output.
  $output = array();

  $output['test'] = array(
    '#markup' => t('ASDF'),
  );

  return $output;
}
