<?php
/**
 * @file
 * Code for Drupal Kitchen Cookoff
 */

 // Load the plugins include, which has a bunch of plugin functions we'll need.
module_load_include('inc', 'dkc_single', 'includes/plugins');

/**
 * Implements hook_menu().
 */
function dkc_single_menu() {
  $items = array();

  // Start page
  $items['start/single'] = array(
    'title' => t('Start a single player game'),
    'page callback' => 'dkc_single_start',
    'access arguments' => array('play single player'),
    'file' => 'includes/pages.inc',
  );

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function dkc_single_form_alter(&$form, &$form_state, $form_id) {
  // Check for a level.
  if (!empty($_GET['level'])) {
    // Load the level.
    $level = dkc_single_get_level_plugin($_GET['level']);

    // Store the level data in form_state.
    $form_state['dkc_level'] = $level;

    // Let the level run it's own form alter.
    if ($function = ctools_plugin_get_function($level, 'form_alter')) {
      $function($form, $form_state, $form_id);
    }
  }
}
