<?php

/**
* Implementation of hook_form_alter().
*/
function esri_search_form_alter(&$form, &$form_state, $form_id) {
  if ( $form_id == 'apachesolr_search_custom_page_search_form' ) {
    $form['basic']['keys']['#title_display'] = 'invisible';

  }
}

/**
* Implementation of hook_js_alter().
*/
function esri_search_js_alter(&$javascript) {
  // Replace accoridion_block module's init file
  if (arg(0) == 'search') {
    $javascript['profiles/dkcookoff/modules/contrib/accordion_blocks/accordion_init.js']['data'] = drupal_get_path('theme', 'esri') . '/js/accordion_init.js';
  }
}

/**
* Implementation of hook_init().
*/
function esri_search_init() {
  if (arg(0) == 'search') {
    drupal_add_js(drupal_get_path('profile', 'dkcookoff').'/libraries/jquery.cookie/jquery.cookie.js');
  }
}

/**
 * Implements hook_facetapi_widgets().
 */
function esri_search_facetapi_widgets() {
  return array(
    'esri_search' => array(
      'handler' => array(
        'label' => t('Date facet links with checkboxes'),
        'class' => 'FacetapiWidgetEsri',
        'query types' => array('date'),
      ),
    ),
  );
}
