<?php
/**
 * @file
 * Code for the Training - content types feature.
 */

include_once 'training_content_types.features.inc';


/**
 * Implements hook_node_update_index()
 * 
 * For training: Provides search index with the data from the course description, 
 * trainer and location nodes associated with the given training node.
 * 
 * For collateral, MA and education: Provides "keyword" terms associated with the node.
 */
function training_content_types_node_update_index($node) {
  $text = '';
  switch ($node->type) {
    case 'training':
      // get associated course description content node
      $cd_node_id = field_get_items('node', $node, 'field_training_course');
      if ($cd_node_id) {
        $cd_node = node_load($cd_node_id[0]['nid']);
        // get description text
        $cd_node_desc = field_get_items('node', $cd_node, 'field_cd_description');
        $text .= $cd_node_desc ? $cd_node_desc[0]['safe_value'] + ' ' : '';
        
        // get keywords
        $cd_node_tags = field_get_items('node', $cd_node, 'field_cd_keywords');
        foreach ($cd_node_tags as $term_array) {
          $term = taxonomy_term_load($term_array['tid']);
          $text .= $term->name . ' ';
        }         
      }    
      break;
    case 'resource_collateral_resources':  
    case 'resource_teaching_materials':
      $node_tags = field_get_items('node', $node, 'field_cr_keywords');
      foreach ($node_tags as $term_array) {
        $term = taxonomy_term_load($term_array['tid']);
        $text .= $term->name . ' ';
      }
      break;
    case 'resource_maps_and_apps':
      $node_tags = field_get_items('node', $node, 'field_ma_keywords');
      foreach ($node_tags as $term_array) {
        $term = taxonomy_term_load($term_array['tid']);
        $text .= $term->name . ' ';
      }    
      break;  
    default:    
  }
  return $text;
}
